apiVersion: v1
kind: ConfigMap
metadata:
  name: vproapp-config
  namespace: {{ include "vprofile.namespace" . }}
  labels:
    {{- include "vprofile.labels" . | nindent 4 }}
data:
  application.properties: |-
{{ .Values.tomcat.config.content | indent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: {{ include "vprofile.namespace" . }}
  labels:
    {{- include "vprofile.labels" . | nindent 4 }}
data:
  vproapp.conf: |-
{{ .Values.nginx.config.content | indent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-config
  namespace: {{ include "vprofile.namespace" . }}
  labels:
    {{- include "vprofile.labels" . | nindent 4 }}
data:
  rabbitmq.conf: |-
{{ .Values.rabbitmq.config.content | indent 4 }}
