apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
  namespace: {{ .Values.namespaceConfig.name }}
  labels:
    app.kubernetes.io/name: db-secrets
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    environment: {{ .Values.global.environment }}
type: Opaque
data:
  root-password: {{ .Values.db.secrets.rootPassword | b64enc }}
  db-password: {{ .Values.db.secrets.dbPassword | b64enc }}
  db-user: {{ .Values.db.secrets.dbUser | b64enc }}
  db-name: {{ .Values.db.secrets.dbName | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secrets
  namespace: {{ .Values.namespaceConfig.name }}
  labels:
    app.kubernetes.io/name: rabbitmq-secrets
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    environment: {{ .Values.global.environment }}
type: Opaque
data:
  rabbitmq-user: {{ .Values.rabbitmq.secrets.user | b64enc }}
  rabbitmq-password: {{ .Values.rabbitmq.secrets.password | b64enc }}