apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.db.name }}
  namespace: {{ include "vprofile.namespace" . }}
  labels:
    {{- include "vprofile.labels" . | nindent 4 }}
type: Opaque
data:
  root-password: {{ .Values.secrets.db.root_password | b64enc }}
  db-password: {{ .Values.secrets.db.db_password | b64enc }}
  db-user: {{ .Values.secrets.db.db_user | b64enc }}
  db-name: {{ .Values.secrets.db.db_name | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.rabbitmq.name }}
  namespace: {{ include "vprofile.namespace" . }}
  labels:
    {{- include "vprofile.labels" . | nindent 4 }}
type: Opaque
data:
  rabbitmq-user: {{ .Values.secrets.rabbitmq.rabbitmq_user | b64enc }}
  rabbitmq-password: {{ .Values.secrets.rabbitmq.rabbitmq_password | b64enc }}
